linters:
  enable-all: true
  disable:
    - gomnd
    - execinquery
    - exportloopref
    - depguard
    - godox
    - gci
    - testpackage
    - exhaustruct
    - gochecknoglobals # store global configuration values
    - forbidigo # use printf for showing progress information and verbose output
    - gochecknoinits # init functions to setup cobra commands
linters-settings:
  gocritic:
    enable-all: true
  funlen:
    lines: 60
    statements: 40
    ignore-comments: true
  paralleltest:
    ignore-missing: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - varnamelen
        - dupl
  exclude-dirs:
    - test/complexity # test code directory
