name: Go PR

on:
  pull_request:
    branches: [ main ]
    types: [opened, reopened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'

    - name: Build
      run: make build

    - name: Test
      run: make test-with-coverage

    - name: Coverage
      id: coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        config: ./.testcoverage.yml
    
    - name: Post coverage report
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          go-test-coverage report:
          ```
          ${{ fromJSON(steps.coverage.outputs.report) }} 
          ```
        edit-mode: replace

    - name: Check coverage
      if: steps.coverage.outcome == 'failure'
      shell: bash
      run: echo "coverage check failed" && exit 1
      
  Lint:
    name: lint
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62
